### ISSUE TITLE
Height of dialog/iframe too small

### ISSUE THREAD

**Issue by schotman** [w8tcha/dnnckeditor#56] opened 2019-05-13 08:24 UTC
The height of dialog (and iframe) too small for image browser, therefore “OK” and “cancel” buttons are not visible (dnn922, CKE 2.1.24)

![image](https://user-images.githubusercontent.com/2582737/57606426-25573980-7569-11e9-8dfa-1de38a3f2cb4.png)

(I highlighted the elements a bit, default Xcillion skin)

**Comment by w8tcha** [comment] 2019-05-13 09:20
Hmh i dont think this can be fixed from within the Editor Provider. The modal window is too small, but this cant be fixed from within the Editor Provider

**Comment by sleupold** [comment] 2019-05-13 09:26
I had the same issue on a small screen, zooming out in the browser (just for saving the image helped).
But IMO caption for the boxes should be in a dedicated column would help - is the alignment by default or caused by an applied skin?

**Comment by schotman** [comment] 2019-05-13 11:26
It is the default skin on a HD screen, so the default DNN dialog is too small for the image dialog, I will investigate, it will probably somewhere in the js related to the "edit content" action of the html module

**Comment by schotman** [comment] 2019-05-16 09:51
I investigated further and found that this only occurs in the default moono-lisa skin. I added some css to overcome this problem, but the dialog.css file is somehow cached with some cache version which I can't seem to get rid of. 

When I apply the below css to the popup skin, the dialog fits the screen again. Maybe you could add it to the next release?


	.cke_dialog_body {
		border: solid 1px #cdcdcd;
	}
	
	.cke_dialog_body .cke_dialog_contents_body .cke_dialog_ui_text, 
	.cke_dialog_body .cke_dialog_contents_body .cke_dialog_ui_select, 
	.cke_dialog_body .cke_dialog_contents_body .cke_dialog_ui_hbox_last > a.cke_dialog_ui_button {
		margin-top: 0px;
	}
	.cke_dialog_body .cke_dialog_title {
		padding: 9px 19px 8px 12px;
	}

**Comment by w8tcha** [comment] 2019-05-16 11:06
i would prefer putting the fix in the editor.css. Otherwise i would have to apply the changes with every upgrade

**Comment by w8tcha** [comment] 2019-05-30 08:26
The fix has been added to the latest release..

https://github.com/w8tcha/dnnckeditor/releases/tag/v02.01.26

**Closed by w8tcha** 2019-05-30 08:26 UTC
